### ISSUE TITLE
Can the firmware code be sourced?

### ISSUE THREAD

**Issue by mmabluesky** [Umang96/munch_custom_pe_rom_releases#2]
as the title, I hope to release the source code, I want to participate in the development of this project, thank you

**Comment by Umang96** [comment]
It's all there and public on my github.

**Comment by mmabluesky** [comment]
> It's all there and public on my github.
Can you guide me? how to compile poco4 of pixel firmware，thanks

**Comment by mmabluesky** [comment]
> It's all there and public on my github.
Can you guide me? how to compile poco4 of pixel firmware，thanks
