### ISSUE TITLE
The screen hollow of redmi k40s has the wrong diameter of the bangs, and the hollow is larger than the original one

### ISSUE THREAD

**Issue by KajiRyouji** [Umang96/munch_custom_pe_rom_releases#3]
In the developer options, the display cutout is switched from the default to other types, and the cutout diameter has become smaller.
Xiaomi customer service responded that the hollow diameter of redmi k40s is only 2.76mm
![IMG_20220829_233047](https://user-images.githubusercontent.com/91704814/187250408-62d38478-4767-402f-91c7-c66f03b452ae.jpg)
![IMG_20220829_233145](https://user-images.githubusercontent.com/91704814/187250442-e8f286d5-2dd8-408d-9f92-e02fbd2c3056.jpg)
[bugreport-aosp_munch-SQ3A.220705.004-2022-08-30-00-15-12.zip](https://github.com/Umang96/munch_custom_pe_rom_releases/files/9446306/bugreport-aosp_munch-SQ3A.220705.004-2022-08-30-00-15-12.zip)

**Comment by Umang96** [comment]
Fixed, please test latest build - 
https://github.com/Umang96/munch_custom_pe_rom_releases/releases/tag/29-Aug-2022

**Comment by KajiRyouji** [comment]
Confirm it has been fixed
