### ISSUE TITLE
how to get root privileges

### ISSUE THREAD

**Issue by pzzmyc** [Umang96/munch_custom_pe_rom_releases#5]
All the features look great，but how to flash magisk？twrp （v3.8.3_A12-munch-skkk_31fedcb1.img）not boot after flash this rom😢

**Comment by PeronGH** [comment]
`fastboot boot TWRP.img`
Then just flash Magisk in the TWRP, and reboot.

**Comment by ad1tyx666** [comment]
So you can use payload dumper to get the boot img and you have to to patch it through the magisk app then you have to flash the boot img in fastboot ,
https://youtu.be/gF5-3aCnG6I here's and tutorial on it
