### ISSUE TITLE
forcing refresh rate causes display issue and google recorder is not working

### ISSUE THREAD

**Issue by iykwimhhe** [Umang96/munch_custom_pe_rom_releases#7]
1. setting force refresh rate value (max and min) to 90hz or setting refresh rate to different max and min value causes greenish color on top part of the screen in when using dark mode.
2. google recorder does not pick up audio when recording

[Build: 31-Aug-2022](https://github.com/Umang96/munch_custom_pe_rom_releases/releases/tag/31-Aug-2022)

**Comment by Umang96** [comment]
1. 90 hz is not officially supported by xiaomi on our panel, it has bad calibration.
2. This is app update issue, use another app for now or uninstall updates of recorder, will remove google recorder in next release.

**Comment by iykwimhhe** [comment]
oh ok, got it
