### ISSUE TITLE
No OTA updates?

### ISSUE THREAD

**Issue by KulkarniKaustubh** [Umang96/munch_custom_pe_rom_releases#8]
Can we expect OTA updates? Always backing up all the data and flashing the updated ROM is a bit frustrating.

**Comment by Umang96** [comment]
No, OTA won't be supported on this, I am currently busy working on 13, will give OTA on my 13 rom.

Also, there is no need to wipe/backup data when you update. Just sideload and reboot.

**Comment by mmabluesky** [comment]
Awesome

**Comment by mmabluesky** [comment]
> No, OTA won't be supported on this, I am currently busy working on 13, will give OTA on my 13 rom.
> 
> Also, there is no need to wipe/backup data when you update. Just sideload and reboot.

Any update ？！😂
